### ISSUE TITLE
TypeError: NetworkError when attempting to fetch resource.

### ISSUE THREAD

**Issue by markmarkinson** [cazala/coin-hive-proxy#2]
Hi,

when i try to load the proxy through firefox following error occures
*TypeError: NetworkError when attempting to fetch resource.*

In Chrome its working fine.

**Comment by cazala** [comment]
Is the resource that cannot be fetch the file `cryptonight-asmjs.min.js.mem`?

**Comment by cazala** [comment]
It was been reported that this proxy is unable to serve the `.mem` and `.wasm` files. That's why it has been deprectated, try to use this instead [CoinHive Proxy](https://coinhive-proxy.party/)
