### ISSUE TITLE
Uncaught (in promise) abort({}) at Error

### ISSUE THREAD

**Issue by ecSpl01t** [cazala/coin-hive-proxy#3]
Hi @cazala,
Do you know how to fix that ?
If I right understand, adblock blocks some transaction.

Uncaught (in promise) abort({}) at Error
    at jsStackTrace (blob:http://site/d2232aeb-d4be-41b4-b8be-6e21c24ea7cb:1:19628)
    at stackTrace (blob:http://site/d2232aeb-d4be-41b4-b8be-6e21c24ea7cb:1:19799)
    at abort (blob:http://site/d2232aeb-d4be-41b4-b8be-6e21c24ea7cb:1:119054)
    at blob:http://site/d2232aeb-d4be-41b4-b8be-6e21c24ea7cb:1:30766
    at <anonymous>
If this abort() is unexpected, build with -s ASSERTIONS=1 which can give more information.
Promise rejected (async)
doNativeWasm @ blob:http://site/d2232aeb-d4be-41b4-b8be-6e21c24ea7cb:1
Module.asm @ blob:http://site/d2232aeb-d4be-41b4-b8be-6e21c24ea7cb:1
(anonymous) @ blob:http://site/d2232aeb-d4be-41b4-b8be-6e21c24ea7cb:1

p.s. I use your proxy link

**Comment by cazala** [comment]
Mmm yea, i think that happens when the cryptonight wasm file fails to load.. The proxy is letting you reach the websocket server, but the extension is blocking the request to the wasm file. 

I probably need to add that one to the repo as well.

**Comment by ecSpl01t** [comment]
Thank you to answered

**Comment by cazala** [comment]
I fixed this in [CoinHive Proxy](https://coinhive-proxy.party/)

**Comment by ecSpl01t** [comment]
@cazala 
I have some problem with proxy:

npm install
10/24 05:01 PM (4h)
⧗ Installing 1 main dependency…
10/24 05:01 PM (4h)
✓ Installed 109 modules [2s]
10/24 05:01 PM (4h)
npm start
10/24 05:01 PM (4h)
npm WARN lifecycle The node binary used for scripts is /home/nowuser/bin/node but npm is using /usr/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.
10/24 05:01 PM (4h)

> proxy@ start /home/nowuser/src
> coin-hive-proxy coinhive
10/24 08:00 PM (53m)
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: socket hang up
    at TLSSocket.onHangUp (_tls_wrap.js:1136:19)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:110:20)
    at TLSSocket.emit (events.js:207:7)
    at endReadableNT (_stream_readable.js:1059:12)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)


https://ibb.co/jivQkm - screenshot
