### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by phr34k0** [cazala/coin-hive-proxy#4]
Would this solution work against Adguard?

Found this reference and rules that Adguard uses.
[GIT](https://gist.github.com/ameshkov/b2e93d9fc7632b583e6430ccd986b368) , 
[Rule List](https://filters.adtidy.org/extension/chromium/filters/2.txt)

It blocks anything with coinhive in it's name even a WebSocket

||coinhive.com^$third-party

**Comment by dennym** [comment]
You could fork the repo and rename it. SO there is no `coin-hive` in the url anymore.

**Comment by phr34k0** [comment]
@dennym Not just the JS though. It's typically everything including websocket. I have no idea how to execute or serve a websocket server

**Comment by dennym** [comment]
Well I did it in my case. Forked the repo. Renamed it (to avoid that now.sh names it con-hive). Made the wasm file available from a different url. Changed the client.js to use that different file url. And it was good to go.

**Comment by phr34k0** [comment]
Welp. Deployment is down. I hate to break it but self host is always the best option. Not sure how to go about doing so with websocket https://zeit-status.co/

**Comment by phr34k0** [comment]
Got it to work :D Thanks again!
