### ISSUE TITLE
cryptonight.wasm is blocked

### ISSUE THREAD

**Issue by webmasterslava** [cazala/coin-hive-proxy#7]
Some Chrome extensions block `cryptonight.wasm` request. Probably need to place it on own server along with `client.js`?

**Comment by phr34k0** [comment]
Host it on your own host or something. I got it to run on mine my running by installing node, npm, npm install --save --save-exact ultron safe-buffer async-limiter and node server.js

**Comment by phr34k0** [comment]
download the cryptonight.wasm from https://coinhive.com/lib/cryptonight.wasm and point that https://coinhive.com/lib to your own server where you host the cryptonight.wasm. Can be dropbox or whatever

**Comment by phr34k0** [comment]
Do note wss is secure like https so just replace wss:// with ws:// and https with http. Is pretty easy

**Comment by phr34k0** [comment]
@webmasterslava You can rename it in your client.js and pull it straight from mine https://phr34k0.github.io/kuku-neneh/ctn.wasm or rehost it from your own git and rename the https://github.com/phr34k0/kuku-neneh/blob/master/ctn.wasm to the first link so it can hotlink to it directly. There's no 

> Header set Access-Control-Allow-Origin

errors and everything is working well on my side.

**Comment by cazala** [comment]
Yes, `cryptonight.wasm` wasn't being served by the proxy. I fixed that in [CoinHive Proxy](https://coinhive-proxy.party/) so the proxy itself serves also the miner.js + cryptonight.wasm
