### ISSUE TITLE
The deployment has been removed.

### ISSUE THREAD

**Issue by ecSpl01t** [cazala/coin-hive-proxy#8]
I used your Coin-proxy and I got some link, for example: https://party-rcprccoylf.now.sh/client?party
and after few minutes -> The deployment has been removed.

**Comment by fogoat** [comment]
Got this e-mail from now.sh:


Our system detected cryptocurrency related activity.

Please note that our OSS tier does not allow hosting miners or proxies of any kind.

If you want your account re-instantiated, please respond to this email.


—
Sergio Xalambrí, Support Engineer at ZEIT

**Comment by ecSpl01t** [comment]
@sunk818 
Did you buy another plan? If yes - did you test that proxy, does it works ?

**Comment by fogoat** [comment]
No, I have Linux server I installed node.js and coin-hive-stratum myself. Since the deployment was removed, I'm not really sure what the code listed was anyway...

**Comment by ecSpl01t** [comment]
I got an answer from support:
"To run any cryptocurrency proxy with Now you need to have at least the Pro plan, miners are not allowed."

**Comment by ecSpl01t** [comment]
If I've own server, can I make a proxy server in my vps/vds, if yes - how ?

@cazala 
@sunk818
Maybe you can help me?

**Comment by cazala** [comment]
Yes, head to https://github.com/cazala/coin-hive-stratum

Sent from my iPhone

On Nov 2, 2017, at 9:05 AM, Viacheslav <notifications@github.com<mailto:notifications@github.com>> wrote:


If I've own server, can I make a proxy server in my vps/vds, if yes - how ?

@cazala<https://github.com/cazala>
@sunk818<https://github.com/sunk818>
Maybe you can help me?
